### PR TITLE
module containing persistence-api compatible with jakarta

### PR DESCRIPTION
**Pull request by maTrojak**

### CODE REVIEW

**Comment by maTrojak** [comment]
created 2 submodules, one for javax one for jakarta. The artifactId values should be checked.

**Comment by maTrojak** [comment]
Creates 2 submodules. One with the old javax naming a one with jakarta naming. Optionally rename the parent and javax-persistence-api module artifact ids (old name of javax-persistence-api was persistence-api).

**Comment by rbygrave** [comment]
> old name of javax-persistence-api was persistence-api

It's a breaking change to rename the existing `persistence-api`.  So although it's more consistent to change it we can't introduce breaking changes unless we really really have to or want to.

>  Optionally rename the parent 

Note that the parent will not matter here because I'll make it a maven reactor and not a parent.  The parent of both the "modules" will be `java11-oss` and the parent will never be released.

> jakarta module-info

For `jakarta-persistence-api` we need the module-info to be consistent with the standard one. This means the module name must be `jakarta.persistence.api`  (and we should not change the module name in the existing persistence.api.


Those are the 3 changes required here. Let me know if you want to do them or want to leave them to me.

**Comment by maTrojak** [comment]
@rbygrave You do it please. I would surely do a mistake somewhere.

**Comment by rbygrave** [comment]
Ok, I think we are all good. I'll close this PR.  Thanks @maTrojak  for your work, the changes that got into master are bascially your changes you did here.

Note that we have released io.ebean:jakarta-persistence-api:3.0 into maven central and have a working PR https://github.com/ebean-orm/ebean/pull/2976 that we can use to build (and test) a Jakarta version of Ebean. I'll probably be chatting you Roland and yourself shortly about some details on Jakarta support.

Thanks again!!

Cheers, Rob.

**Pull request closed without merging**
